name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          go build cmd/cochl-mcp-server/main.go

      - name: Test
        run: |
          go test -v -cover ./...
